### PR TITLE
fix: Selecting a group may cause selection of duplicate items (#945)

### LINKED ISSUE #945: Selecting a group may cause selection of duplicate items
### Reproduction Link
https://vue-multiselect.js.org/#sub-option-groups
### Steps to reproduce
1.  Open groups multi-select and select the item **Vue.js**
2. Open again groups multi-select and select group **Javascript**
### Expected behaviour
Only Vue and Adonis should be selected ex: [Vue, Adonis]
### Actual behaviour
Vue gets selected two times ex: [Vue, Vue, Adonis]

### PR DESCRIPTION
**Pull request by akki-jat**
- Closes #945

### CODE REVIEW

File: src/multiselectMixin.js [hunk 1]
```diff
@@ -560,7 +560,9 @@ export default {
 
         this.$emit('input', newValue, this.id)
       } else {
-        const optionsToAdd = group[this.groupValues].filter(not(this.isOptionDisabled || this.isSelected))
```
Comment (akki-jat) [inline src/multiselectMixin.js]: The problem here was that **not** function takes **a function** as parameter and as the name suggests performs not operation on it's response and we were passing two functions separated by pipe as parameter so it always takes first function - isOptionDisabled (takes second function - isSelected only when first function is null / undefined - which is not the case here)

**Comment by shentao** [comment]
This looks amazing! Thanks a lot for also including a test for it. Really appreciate it. Gonna make a release today.
